ccflags-y := -Wall -g -DDEBUG -I$(src)/include

obj-m = xp80-Pcie-Endpoint.o

ifeq ($(NETDEV), 0)
ccflags-y += -DNO_NETDEV
xp80-Pcie-Endpoint-y := \
                        src/xp_pcie_slave.o  
else
xp80-Pcie-Endpoint-y := \
                        src/xp_pcie_slave.o \
                        src/xp_netdev_core.o \
                        src/xp_netdev_proc.o \
                        src/xp_netdev_intf.o \

endif
